# Generated by Django 2.1.4 on 2018-12-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20181214_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=None, max_length=12),
        ),
    ]
