# Generated by Django 2.1.4 on 2018-12-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
