# Generated by Django 2.1.4 on 2018-12-25 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_password2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
