# Generated by Django 2.1.4 on 2018-12-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=13)),
                ('email', models.EmailField(default='', max_length=50)),
                ('user_name', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
