# Generated by Django 2.1.4 on 2018-12-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
