# Generated by Django 2.1.4 on 2018-12-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20181227_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='product',
            new_name='course',
        ),
    ]
